SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
AvgEnergy Class Reference
Public Member Functions
AvgEnergy (char *audioFile, char *metaIn)
~AvgEnergy ()
Constructor & Destructor Documentation
AvgEnergy::AvgEnergy (char * audioFile, char * metaIn)
References FeaturePool::claimSegmentationID(), FILE_TYPE_RAW_SAD, FeaturePool::getAverageEnergy(), FeaturePool::readRTTM(), and FeaturePool::retrieveEnergy().
AvgEnergy::~AvgEnergy ()
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:42:44 2010 for 'shout' by doxygen 1.5.8.