SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutSegment Class Reference
Public Member Functions
ShoutSegment (char *featureFile, FILE *amFile, char *rttmOut, char *label, char *UEM, bool widenSegments, char *ctsInName, char *ctsOutName, bool energyBased)
~ShoutSegment ()
Protected Member Functions
void trainModel (TrainPhoneModel *model, int nr, bool waitForMe)
void doSAD_noGarbage (FeaturePool *featurePool, int segID, int silID, int speechID, int chunks)
Protected Attributes
int uemID
Constructor & Destructor Documentation
ShoutSegment::ShoutSegment (char * featureFile, FILE * amFile, char * rttmOut, char * label, char * UEM, bool widenSegments, char * ctsInName, char * ctsOutName, bool energyBased)
References FeaturePool::addSegment(), FeaturePool::claimSegmentationID(), FeaturePool::concatSegmentation(), Segmenter::createLexicalTree(), FeaturePool::createUEMSegmentation(), doSAD_noGarbage(), Segmenter::featurePool, FILE_TYPE_RAW_SAD, FeaturePool::filterShortSegments(), FeaturePool::getClusterLength(), FeaturePool::getCurSegmentLen(), FeaturePool::getCurSegmentStart(), FeaturePool::getFirstVectorFirstSegment(), FeaturePool::getFirstVectorNextSegment(), FeaturePool::getPoolLength(), FeaturePool::getSegmentID(), TrainPhoneModel::getTrainSilP(), FeaturePool::getVectorSize(), FeaturePool::maxSegmentLength(), FeaturePool::mergeLabels(), MINPASSES, Segmenter::numberOfClusters, LexicalTree::numberOfPhones, LexicalTree::phoneModels, FeaturePool::removeLowEnergy(), FeaturePool::resetSegmentation(), FeaturePool::retrieveEnergy(), FeaturePool::segmentationCopy(), FeaturePool::segmentationIntersection(), Segmenter::segmentFeaturePool(), TrainPhoneModel::setTrainingData(), FeaturePool::splitOnEnergy(), TrainPhoneModel::train(), trainModel(), uemID, and FeaturePool::writeRTTM().
ShoutSegment::~ShoutSegment ()
Todo:
Documentation
Member Function Documentation
void ShoutSegment::doSAD_noGarbage (FeaturePool * featurePool, int segID, int silID, int speechID, int chunks) [protected]
Todo:
Documentation
References FeaturePool::getClusterLength(), FeaturePool::getVectorSize(), MINPASSES, LexicalTree::phoneModels, FeaturePool::resetSegmentation(), FeaturePool::segmentationCopy(), FeaturePool::segmentationSubset(), Segmenter::segmentFeaturePool(), TrainPhoneModel::setTrainingData(), trainModel(), and uemID.
Referenced by ShoutSegment().
void ShoutSegment::trainModel (TrainPhoneModel * model, int nr, bool waitForMe) [protected]
Helper function for threads, so that we don't need compile switches all over my code.
References condition_shoutsegment_mutexDone, condition_shoutSegment_mutexStart, condition_shoutsegment_threadDone, condition_shoutSegment_threadStart, Thread_Train_Data::model, Thread_Train_Data::nr, shoutsegment_threadMayStart, shoutsegment_threadRunning, and TrainPhoneModel::train().
Referenced by doSAD_noGarbage(), and ShoutSegment().
Member Data Documentation
int ShoutSegment::uemID [protected]
Referenced by doSAD_noGarbage(), and ShoutSegment().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:24 2010 for 'shout' by doxygen 1.5.8.