SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
SpkrecStats Class Reference
Public Member Functions
SpkrecStats (char *ubmFile, char *audioFile, char *metaInFile, bool outputStats)
~SpkrecStats ()
Private Member Functions
void readUbmModel (char *modelName)
Private Attributes
PhoneModel * ubm
int vectorSize
Constructor & Destructor Documentation
SpkrecStats::SpkrecStats (char * ubmFile, char * audioFile, char * metaInFile, bool outputStats)
Todo:
docs
References PhoneModel::adapt_clear(), PhoneModel::adapt_setAcumulators(), FeaturePool::claimSegmentationID(), FeaturePool::createNewPool(), FILE_TYPE_RAW_SPKREC, FeaturePool::getNumberOfSpeakers(), FeaturePool::getSpeakerID(), FeaturePool::getVectorSize(), PhoneModel::printModel(), FeaturePool::readRTTM(), readUbmModel(), FeaturePool::storeFeatureVectors(), ubm, vectorSize, and PhoneModel::writeAccumulators().
SpkrecStats::~SpkrecStats ()
Todo:
docs
References ubm.
Member Function Documentation
void SpkrecStats::readUbmModel (char * modelName) [private]
Todo:
docs
References WriteFileLittleBigEndian::freadEndianSafe(), ubm, and vectorSize.
Referenced by SpkrecStats().
Member Data Documentation
PhoneModel* SpkrecStats::ubm [private]
Referenced by readUbmModel(), SpkrecStats(), and ~SpkrecStats().
int SpkrecStats::vectorSize [private]
Referenced by readUbmModel(), and SpkrecStats().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:28 2010 for 'shout' by doxygen 1.5.8.