SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
MergeTrainSet Class Reference
Public Member Functions
MergeTrainSet (char *task, char *phoneList, char *traindir1, char *traindir2)
~MergeTrainSet ()
Constructor & Destructor Documentation
MergeTrainSet::MergeTrainSet (char * task, char * phoneList, char * traindir1, char * traindir2)
References Shout_MakeTrainSet::data, WriteFileLittleBigEndian::freadEndianSafe(), Vector::getValue(), DataStats::name, Shout_MakeTrainSet::nrOfModels, DataStats::nrOfSamples, Shout_MakeTrainSet::nrOfSil, Shout_MakeTrainSet::performWhat, Shout_MakeTrainSet::phoneFile, Vector::storeData(), TASK_TYPE_ARTICULATORY, Shout_MakeTrainSet::totalPhonesStored, and Shout_MakeTrainSet::vectorSize.
MergeTrainSet::~MergeTrainSet ()
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:07 2010 for 'shout' by doxygen 1.5.8.