SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
NormalizeAM Class Reference
Public Member Functions
NormalizeAM (char *inFile, char *rttmFile)
~NormalizeAM ()
Constructor & Destructor Documentation
NormalizeAM::NormalizeAM (char * inFile, char * rttmName)
Todo:
Doc
References FeaturePool::claimSegmentationID(), FeaturePool::createNewPool(), FILE_TYPE_RAW_DECODING, and FeaturePool::readRTTM().
NormalizeAM::~NormalizeAM ()
Todo:
Doc
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:13 2010 for 'shout' by doxygen 1.5.8.