SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
Adapt_AM Class Reference
The Adapt_AM class is the main class of the shout_adapt_am application.
Public Member Functions
Adapt_AM (char *adapt_dir, char *amName, char *clusterAM, char *newAmName)
~Adapt_AM ()
Public Attributes
TrainPhoneModel ** models
Detailed Description
The Adapt_AM class is the main class of the shout_adapt_am application.
The constructor will be called by the main() function. All work will be done in the constructor. The acoustic data will be loaded and passed to the structured tree class Adapt_AM_TreeNode.
The general call order of the methods used is:
TrainPhoneModel::adapt_setAcumulators()
Create a new Adapt_AM_TreeNode object.
Create the meanGaussian (Gaussian) object of the Adapt_AM_TreeNode object
TrainPhoneModel::adapt_setInitialNode()
Call Adapt_AM_TreeNode::split() and re-set the gaussians with TrainPhoneModel::adapt_setNode() (recursively)
Call Adapt_AM_TreeNode::setHelperMatrices_1() and Adapt_AM_TreeNode::setHelperMatrices_2()
The adaptation matrices are now calculated and can be used by Gaussian::adapt_adapt() and (un-used) by Gaussian::adapt_unAdapt()
Constructor & Destructor Documentation
Adapt_AM::Adapt_AM (char * adapt_dir, char * amName, char * clusterAM, char * newAmName)
The constructor will check the directory that contains the adaptation data, load the data and pass it to Adapt_AM_TreeNode. The resulting model will be stored to disc.
References PhoneModel::adapt_adapt(), PhoneModel::adapt_adaptVar(), PhoneModel::adapt_setInitialNode(), PhoneModel::adapt_setNode(), PhoneModel::adapt_setVarTrans(), FeaturePool::addSegment(), WriteFileLittleBigEndian::freadEndianSafe(), PhoneModel::mapAdaptMeans(), Adapt_AM_TreeNode::meanGaussian, models, FeaturePool::setCurSegmentVectors(), Adapt_AM_TreeNode::setHelperMatrices_1(), Adapt_AM_TreeNode::setHelperMatrices_2(), TrainPhoneModel::setTrainingData(), Adapt_AM_TreeNode::split(), and PhoneModel::writeModel().
Adapt_AM::~Adapt_AM ()
The destructor is empty.
Member Data Documentation
TrainPhoneModel** Adapt_AM::models
Referenced by Adapt_AM().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:42:42 2010 for 'shout' by doxygen 1.5.8.