SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutTrainModel Class Reference
Public Member Functions
ShoutTrainModel (char *dataDir, char *decisionRulesName, char *existingAM, int modelNumber, int maxGaussians, int trainSilP, int trainSilMax, char *doFast)
~ShoutTrainModel ()
Constructor & Destructor Documentation
ShoutTrainModel::ShoutTrainModel (char * dataDir, char * decisionRulesName, char * existingAM, int modelNumber, int maxGaussians, int trainSilP, int trainSilMax, char * doFast)
References FeaturePool::addSegment(), WriteFileLittleBigEndian::freadEndianSafe(), PhoneModel::getStatistics(), ModelStats::nrOfContexts, ModelStats::nrOfGaussians, DataStats::nrOfSamples, ModelStats::nrOfTrainOcc, FeaturePool::resetSegmentation(), FeaturePool::setCurSegmentVectors(), TrainPhoneModel::setDecisionMatrix(), TrainPhoneModel::setTrainingData(), TrainPhoneModel::train(), PhoneModel::writeModel(), and TrainPhoneModel::writeSAT().
ShoutTrainModel::~ShoutTrainModel ()
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:25 2010 for 'shout' by doxygen 1.5.8.