SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
Shout_Preprocess Class Reference
Public Member Functions
Shout_Preprocess (char *phoneList, char *traindir, char *audioList, char *amPhone)
~Shout_Preprocess ()
Private Attributes
DataStats * data
int nrOfModels
int nrOfSil
int vectorSize
bool doStateLabeling
PhoneModel ** models
Detailed Description
Todo:
Docs
Constructor & Destructor Documentation
Shout_Preprocess::Shout_Preprocess (char * phoneList, char * traindir, char * audioList, char * amPhone)
Todo:
Docs
References FeaturePool::claimSegmentationID(), FeaturePool::createNewPool(), data, doStateLabeling, FILE_TYPE_RAW_DECODING, WriteFileLittleBigEndian::freadEndianSafe(), FeaturePool::getPoolLength(), PhoneModel::getStateNr(), models, nrOfModels, nrOfSil, FeaturePool::readRTTM(), FeaturePool::setOnlyMEL(), FeaturePool::storeFeatureVectors(), and vectorSize.
Shout_Preprocess::~Shout_Preprocess ()
Todo:
Docs
References models, and nrOfModels.
Member Data Documentation
DataStats* Shout_Preprocess::data [private]
Referenced by Shout_Preprocess().
bool Shout_Preprocess::doStateLabeling [private]
Referenced by Shout_Preprocess().
PhoneModel** Shout_Preprocess::models [private]
Referenced by Shout_Preprocess(), and ~Shout_Preprocess().
int Shout_Preprocess::nrOfModels [private]
Referenced by Shout_Preprocess(), and ~Shout_Preprocess().
int Shout_Preprocess::nrOfSil [private]
Referenced by Shout_Preprocess().
int Shout_Preprocess::vectorSize [private]
Referenced by Shout_Preprocess().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:22 2010 for 'shout' by doxygen 1.5.8.