SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutOnline Class Reference
Public Member Functions
ShoutOnline (char *amName, char *lexName, char *lmName, char *latName, char *configDir)
~ShoutOnline ()
Protected Member Functions
int determineAction (double testSil, bool *isSil)
Protected Attributes
int silCounter
int numberOfModels
int numberOfClusters
int vectorSize
PhoneModel ** models
LexicalTree * myTree
LanguageModel * myLM
Constructor & Destructor Documentation
ShoutOnline::ShoutOnline (char * amName, char * lexName, char * lmName, char * latName, char * configDir)
References condition_mutexDoneOnline, condition_mutexStartOnline, condition_threadStartOnline, Vector::copyVector(), determineAction(), FeatureExtraction::doFeatureExtraction(), FEATURENORM_ALL, WriteFileLittleBigEndian::freadEndianSafe(), WriteFileLittleBigEndian::fwriteEndianSafe(), LexicalTree::getBestIDSequence(), Gaussian::getMean(), FeatureExtraction::getOnlineVector(), Vector::getValue(), Gaussian::getVariance(), LexicalTree::getWord(), LexicalTree::getWordID(), LexicalTree::initialiseTree(), models, myLM, myTree, Thread_online_Data::number, numberOfClusters, numberOfModels, LexicalTree::overwritePrunePars(), LexicalTree::overwriteWeightPars(), LexicalTree::printInitialSettings(), LexicalTree::processVector(), Thread_online_Data::quit, Thread_online_Data::result, LexicalTree::setAMs(), FeatureExtraction::setAudioFileOut(), LexicalTree::setLattice(), LexicalTree::setLM(), FeatureExtraction::setNormalization(), FeatureExtraction::setVTLN(), silCounter, thread_online(), Thread_online_Data::threadID, threadMayStartOnline, threadOnline, vectorSize, and vtlnThreadFinished.
ShoutOnline::~ShoutOnline ()
References condition_mutexStartOnline, condition_threadStartOnline, models, myLM, myTree, numberOfModels, Thread_online_Data::quit, threadMayStartOnline, and threadOnline.
Member Function Documentation
int ShoutOnline::determineAction (double testSil, bool * isSil) [protected]
References silCounter.
Referenced by ShoutOnline().
Member Data Documentation
PhoneModel** ShoutOnline::models [protected]
Referenced by ShoutOnline(), and ~ShoutOnline().
LanguageModel* ShoutOnline::myLM [protected]
Referenced by ShoutOnline(), and ~ShoutOnline().
LexicalTree* ShoutOnline::myTree [protected]
Referenced by ShoutOnline(), and ~ShoutOnline().
int ShoutOnline::numberOfClusters [protected]
Referenced by ShoutOnline().
int ShoutOnline::numberOfModels [protected]
Referenced by ShoutOnline(), and ~ShoutOnline().
int ShoutOnline::silCounter [protected]
Referenced by determineAction(), and ShoutOnline().
int ShoutOnline::vectorSize [protected]
Referenced by ShoutOnline().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:23 2010 for 'shout' by doxygen 1.5.8.