SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
StringLookup Class Reference
Public Member Functions
StringLookup (int numberOfWords, char **vocabulary)
~StringLookup ()
int getWordID (char *word)
Protected Member Functions
void deleteWordTree (WordStringNode *w)
Protected Attributes
WordStringNode * wordTree
Detailed Description
Todo:
Docs
Constructor & Destructor Documentation
StringLookup::StringLookup (int numberOfWords, char ** vocabulary)
Creates a tree-structure of all words. This will make getWordID a lot faster, but it costs memory!
References WordStringNode::c, WordStringNode::next, WordStringNode::par, WordStringNode::wordID, and wordTree.
StringLookup::~StringLookup ()
Todo:
Docs
References deleteWordTree(), and wordTree.
Member Function Documentation
void StringLookup::deleteWordTree (WordStringNode * w) [protected]
Deletes the word tree.
References WordStringNode::next, and WordStringNode::par.
Referenced by ~StringLookup().
int StringLookup::getWordID (char * word)
Returns the ID of the word 'word'. If the word is not in the vocabulary (OOV), -1 is returned.
References WordStringNode::c, WordStringNode::next, WordStringNode::par, WordStringNode::wordID, and wordTree.
Referenced by ShoutConfig::fillParameter(), and Shout_lm2bin::Shout_lm2bin().
Member Data Documentation
WordStringNode* StringLookup::wordTree [protected]
Referenced by getWordID(), StringLookup(), and ~StringLookup().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:28 2010 for 'shout' by doxygen 1.5.8.