SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
FFTReal::FFTReal::TrigoLUT Class Reference
The FFT procedures used by shout are written by Laurent de Soras.
Public Member Functions
TrigoLUT (const int nbr_bits)
~TrigoLUT ()
const flt_t * get_ptr (const int level) const
Private Attributes
flt_t * _ptr
Detailed Description
The FFT procedures used by shout are written by Laurent de Soras.
This is his legal message:
LEGAL
Source code may be freely used for any purpose, including commercial applications. Programs must display in their "About" dialog-box (or documentation) a text telling they use these routines by Laurent de Soras. Modified source code can be distributed, but modifications must be clearly indicated.
CONTACT
Laurent de Soras 92 avenue Albert 1er 92500 Rueil-Malmaison France
ldesoras@club-internet.fr
Constructor & Destructor Documentation
FFTReal::FFTReal::TrigoLUT::TrigoLUT (const int nbr_bits) [explicit]
The FFT procedures used by shout are written by Laurent de Soras
References FFTReal::FFTReal::TrigoLUT::_ptr, and FFTReal::FFTReal::TrigoLUT::get_ptr().
FFTReal::FFTReal::TrigoLUT::~TrigoLUT (void)
The FFT procedures used by shout are written by Laurent de Soras
References FFTReal::FFTReal::TrigoLUT::_ptr.
Member Function Documentation
const flt_t* FFTReal::FFTReal::TrigoLUT::get_ptr (const int level) const [inline]
References FFTReal::FFTReal::TrigoLUT::_ptr.
Referenced by FFTReal::do_fft(), FFTReal::do_ifft(), and FFTReal::FFTReal::TrigoLUT::TrigoLUT().
Member Data Documentation
flt_t* FFTReal::FFTReal::TrigoLUT::_ptr [private]
Referenced by FFTReal::FFTReal::TrigoLUT::get_ptr(), FFTReal::FFTReal::TrigoLUT::TrigoLUT(), and FFTReal::FFTReal::TrigoLUT::~TrigoLUT().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:42:51 2010 for 'shout' by doxygen 1.5.8.