SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutConfig Class Reference
Public Member Functions
ShoutConfig (APPLICATION_ID appID, int argc, char *argv[])
~ShoutConfig ()
bool parIsDefined (int parameter)
char * getStringValue (int parameter)
float getFloatValue (int parameter)
Protected Member Functions
void initializeParameter (int id, const char *shortDiscr, const char *longDiscr, const char *text, const char *valDiscr, double val)
void initializeParameter (int id, const char *shortDiscr, const char *longDiscr, const char *text, const char *valDiscr, const char *val)
int parInApp (int i)
void readConfigFile (FILE *config, StringLookup *lookupLong)
bool fillParameter (char *line, StringLookup *lookupLong)
Protected Attributes
char ** parShort
char ** parLong
CommandParameterType * parameter
int nrPars
APPLICATION_ID applicationID
Detailed Description
Todo:
docs
Constructor & Destructor Documentation
ShoutConfig::ShoutConfig (APPLICATION_ID appID, int argc, char * argv[])
Todo:
docs
References APPID_ADAPT_AM, APPID_AVG_ENERGY, APPID_CLUSTER, APPID_DCT2LEXTREE, APPID_EXPAND_VOCAB, APPID_LM2BIN, APPID_MAKETRAINSET, APPID_MERGE_AM, APPID_MERGETRAINSET, APPID_NORMALIZE_AM, APPID_PREPARE_ADAPT, APPID_PREPROCESS, APPID_SEGMENT, APPID_SHOUT, APPID_SHOUTONLINE, APPID_SPKREC, APPID_SPKRECSTATS, APPID_TRAIN_FINISH, APPID_TRAIN_FINISH_SAT, APPID_TRAIN_MMI, APPID_TRAIN_MODEL, APPID_UPDATE_VERSION, APPID_VTLN, applicationID, fillParameter(), initializeParameter(), parameter, parInApp(), parIsDefined(), parLong, parShort, and readConfigFile().
ShoutConfig::~ShoutConfig ()
Todo:
docs
References parameter, parLong, and parShort.
Member Function Documentation
bool ShoutConfig::fillParameter (char * line, StringLookup * lookupLong) [protected]
Todo:
docs
References StringLookup::getWordID(), parameter, StringFunctions::RightTrim(), and StringFunctions::splitList().
Referenced by readConfigFile(), and ShoutConfig().
float ShoutConfig::getFloatValue (int par)
Todo:
docs
References parameter, and parInApp().
Referenced by main(), and Whisper::Whisper().
char * ShoutConfig::getStringValue (int par)
Todo:
docs
References parameter, parInApp(), and CommandParameterType::value.
Referenced by main(), and Whisper::Whisper().
void ShoutConfig::initializeParameter (int id, const char * shortDiscr, const char * longDiscr, const char * text, const char * valDescr, const char * val) [protected]
Todo:
docs
References parameter, parLong, and parShort.
void ShoutConfig::initializeParameter (int id, const char * shortDiscr, const char * longDiscr, const char * text, const char * valDescr, double val) [protected]
Todo:
docs
Referenced by ShoutConfig().
int ShoutConfig::parInApp (int i) [protected]
Todo:
docs
References APPID_ADAPT_AM, APPID_AVG_ENERGY, APPID_CLUSTER, APPID_DCT2LEXTREE, APPID_EXPAND_VOCAB, APPID_LM2BIN, APPID_MAKETRAINSET, APPID_MERGE_AM, APPID_MERGETRAINSET, APPID_NORMALIZE_AM, APPID_PREPARE_ADAPT, APPID_PREPROCESS, APPID_SEGMENT, APPID_SHOUT, APPID_SHOUTONLINE, APPID_SPKREC, APPID_SPKRECSTATS, APPID_TRAIN_FINISH, APPID_TRAIN_FINISH_SAT, APPID_TRAIN_MMI, APPID_TRAIN_MODEL, APPID_UPDATE_VERSION, APPID_VTLN, and applicationID.
Referenced by getFloatValue(), getStringValue(), and ShoutConfig().
bool ShoutConfig::parIsDefined (int par)
Todo:
docs
References parameter.
Referenced by main(), ShoutConfig(), and Whisper::Whisper().
void ShoutConfig::readConfigFile (FILE * config, StringLookup * lookupLong) [protected]
Todo:
docs
References fillParameter().
Referenced by ShoutConfig().
Member Data Documentation
APPLICATION_ID ShoutConfig::applicationID [protected]
Referenced by parInApp(), and ShoutConfig().
int ShoutConfig::nrPars [protected]
CommandParameterType* ShoutConfig::parameter [protected]
Referenced by fillParameter(), getFloatValue(), getStringValue(), initializeParameter(), parIsDefined(), ShoutConfig(), and ~ShoutConfig().
char** ShoutConfig::parLong [protected]
Referenced by initializeParameter(), ShoutConfig(), and ~ShoutConfig().
char** ShoutConfig::parShort [protected]
Referenced by initializeParameter(), ShoutConfig(), and ~ShoutConfig().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:23 2010 for 'shout' by doxygen 1.5.8.