SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
SpeakerRecognition Class Reference
Public Member Functions
SpeakerRecognition (char *ubmMaleFile, char *ubmFemaleFile, char *tasklist, char *modelDir, char *outputPrefix, char *znormList, bool outputStats)
~SpeakerRecognition ()
Private Member Functions
void readUbmModel (char *modelName, bool male)
PhoneModel * readModel (char *modelName, bool applyZNorm)
void writeModel (char *modelName, PhoneModel *model)
Gaussian * runTrials (char *tasklist, char *modelDir, char *outputPrefix, PhoneModel *zNormSpeakerModel=NULL)
Private Attributes
int vectorSize
PhoneModel * ubmMale [MAX_UBMSIZE]
PhoneModel * ubmFemale [MAX_UBMSIZE]
double ubmZNormMean [2][MAX_UBMSIZE]
double ubmZNormVariance [2][MAX_UBMSIZE]
bool ubmZNormAvailable [2]
SegmentationAdmin readPool_curSeg
bool zNormAvailable
double zNormMean
double zNormVariance
int nrUbmMale
int nrUbmFemale
bool outputStats
Constructor & Destructor Documentation
SpeakerRecognition::SpeakerRecognition (char * ubmMaleFile, char * ubmFemaleFile, char * tasklist, char * modelDir, char * outputPrefix, char * znormList, bool outputS)
Todo:
Docs
References Gaussian::getMean(), Vector::getValue(), Gaussian::getVariance(), nrUbmFemale, nrUbmMale, outputStats, PhoneModel::printModel(), readModel(), readUbmModel(), runTrials(), ubmFemale, ubmMale, vectorSize, writeModel(), zNormAvailable, zNormMean, and zNormVariance.
SpeakerRecognition::~SpeakerRecognition ()
Todo:
docs
References ubmFemale, and ubmMale.
Member Function Documentation
PhoneModel * SpeakerRecognition::readModel (char * modelName, bool applyZNorm) [private]
Todo:
docs
References WriteFileLittleBigEndian::freadEndianSafe(), vectorSize, zNormAvailable, zNormMean, and zNormVariance.
Referenced by runTrials(), and SpeakerRecognition().
void SpeakerRecognition::readUbmModel (char * modelName, bool male) [private]
Todo:
docs
References WriteFileLittleBigEndian::freadEndianSafe(), nrUbmFemale, nrUbmMale, ubmFemale, ubmMale, ubmZNormAvailable, ubmZNormMean, ubmZNormVariance, and vectorSize.
Referenced by SpeakerRecognition().
Gaussian * SpeakerRecognition::runTrials (char * tasklist, char * modelDir, char * outputPrefix, PhoneModel * zNormSpeakerModel = NULL) [private]
Todo:
docs
References FeaturePool::claimSegmentationID(), FeaturePool::createNewPool(), FILE_TYPE_RAW_SPKREC, FeaturePool::getCurSegmentLen(), FeaturePool::getCurSegmentStart(), FeaturePool::getFirstVectorFirstSegment(), FeaturePool::getFirstVectorNextSegment(), PhoneModel::getLookaheadLogP(), Gaussian::getMean(), Vector::getValue(), Gaussian::getVariance(), FeaturePool::getVectorList(), FeaturePool::getVectorSize(), nrUbmFemale, nrUbmMale, outputStats, readModel(), readPool_curSeg, FeaturePool::readRTTM(), Vector::setValue(), Gaussian::train(), Gaussian::trainFinish(), ubmFemale, ubmMale, ubmZNormMean, ubmZNormVariance, vectorSize, zNormAvailable, zNormMean, and zNormVariance.
Referenced by SpeakerRecognition().
void SpeakerRecognition::writeModel (char * modelName, PhoneModel * model) [private]
Todo:
docs
References WriteFileLittleBigEndian::fwriteEndianSafe(), vectorSize, PhoneModel::writeModel(), zNormAvailable, zNormMean, and zNormVariance.
Referenced by SpeakerRecognition().
Member Data Documentation
int SpeakerRecognition::nrUbmFemale [private]
Referenced by readUbmModel(), runTrials(), and SpeakerRecognition().
int SpeakerRecognition::nrUbmMale [private]
Referenced by readUbmModel(), runTrials(), and SpeakerRecognition().
bool SpeakerRecognition::outputStats [private]
Referenced by runTrials(), and SpeakerRecognition().
SegmentationAdmin SpeakerRecognition::readPool_curSeg [private]
Referenced by runTrials().
PhoneModel* SpeakerRecognition::ubmFemale[MAX_UBMSIZE] [private]
Referenced by readUbmModel(), runTrials(), SpeakerRecognition(), and ~SpeakerRecognition().
PhoneModel* SpeakerRecognition::ubmMale[MAX_UBMSIZE] [private]
Referenced by readUbmModel(), runTrials(), SpeakerRecognition(), and ~SpeakerRecognition().
bool SpeakerRecognition::ubmZNormAvailable[2] [private]
Referenced by readUbmModel().
double SpeakerRecognition::ubmZNormMean[2][MAX_UBMSIZE] [private]
Referenced by readUbmModel(), and runTrials().
double SpeakerRecognition::ubmZNormVariance[2][MAX_UBMSIZE] [private]
Referenced by readUbmModel(), and runTrials().
int SpeakerRecognition::vectorSize [private]
Referenced by readModel(), readUbmModel(), runTrials(), SpeakerRecognition(), and writeModel().
bool SpeakerRecognition::zNormAvailable [private]
Referenced by readModel(), runTrials(), SpeakerRecognition(), and writeModel().
double SpeakerRecognition::zNormMean [private]
Referenced by readModel(), runTrials(), SpeakerRecognition(), and writeModel().
double SpeakerRecognition::zNormVariance [private]
Referenced by readModel(), runTrials(), SpeakerRecognition(), and writeModel().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:27 2010 for 'shout' by doxygen 1.5.8.