SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
Adapt_Segmenter Class Reference
Public Member Functions
Adapt_Segmenter (FeaturePool *fp, int sID_train, int sID_decode, char *name, int sysID)
~Adapt_Segmenter ()
void createFixedModels (int nrSpkrs, int fixedSeg)
Protected Member Functions
void startMergeIteration ()
double getMergeModelScore (int model1, int model2, int method)
bool proceedMerge (int model1, int model2, int method)
void mergeModels (int model1, int model2)
double getMatrixScore (int a, int model1, int model2, int data1, int data2, int seg)
double trainModel (int model, int nrG)
void adaptModel (TrainPhoneModel *model)
Protected Attributes
int winnerM1
int winnerM2
double mergeWinThreshold
TrainPhoneModel ** compareModels
int nrCompareModels
int ubm_word_amount
int fixedSpeakers
int systemID
int segAmount
double maxDistance
double * pTable1
double * pTable2
int pTlen
char label [100]
int * modelMapping
int segInitID
TrainPhoneModel ** masterAdapt
TrainPhoneModel ** adaptedModel
TrainPhoneModel ** mergeTestMod
int * helpID
Constructor & Destructor Documentation
Adapt_Segmenter::Adapt_Segmenter (FeaturePool * fp, int sID_train, int sID_decode, char * name, int sysID)
Initialize...
References Train_Segmenter::compareClusters, compareModels, and LexicalTree::numberOfPhones.
Adapt_Segmenter::~Adapt_Segmenter ()
Clean up..
Member Function Documentation
void Adapt_Segmenter::adaptModel (TrainPhoneModel * model) [protected]
Todo:
add documentation
References PhoneModel::adapt_adapt(), PhoneModel::adapt_clear(), PhoneModel::adapt_setInitialNode(), PhoneModel::dim(), PhoneModel::isSilModel(), Adapt_AM_TreeNode::meanGaussian, Adapt_AM_TreeNode::setHelperMatrices_1(), and Adapt_AM_TreeNode::setHelperMatrices_2().
void Adapt_Segmenter::createFixedModels (int nrSpkrs, int fixedSeg)
double Adapt_Segmenter::getMatrixScore (int a, int model1, int model2, int data1, int data2, int seg) [protected]
double Adapt_Segmenter::getMergeModelScore (int model1, int model2, int useMethod) [protected]
Merges two single models and determine the score
void Adapt_Segmenter::mergeModels (int model1, int model2) [protected, virtual]
Merges two single models (over loaded by Adapt_Segmenter)
Reimplemented from Train_Segmenter.
bool Adapt_Segmenter::proceedMerge (int model1, int model2, int method) [protected, virtual]
We have decided on two merge candidates. Now determine if we should actually do it, or just stop.
Reimplemented from Train_Segmenter.
References FeaturePool::claimSegmentationID(), Train_Segmenter::compareClusters, compareModels, Segmenter::featurePool, FeaturePool::getClusterLength(), PhoneModel::getNumberOfGaussians(), TrainPhoneModel::getTrainSilP(), LexicalTree::numberOfPhones, Train_Segmenter::sadID_train, Train_Segmenter::segID, FeaturePool::segmentationCopy(), Segmenter::segmentFeaturePool(), TrainPhoneModel::setTrainingData(), TrainPhoneModel::train(), Train_Segmenter::trainCluster, winnerM1, and winnerM2.
void Adapt_Segmenter::startMergeIteration () [protected, virtual]
Todo:
docs
Reimplemented from Train_Segmenter.
double Adapt_Segmenter::trainModel (int model, int nrG) [protected]
Member Data Documentation
TrainPhoneModel** Adapt_Segmenter::adaptedModel [protected]
TrainPhoneModel** Adapt_Segmenter::compareModels [protected]
Referenced by Adapt_Segmenter(), and proceedMerge().
int Adapt_Segmenter::fixedSpeakers [protected]
int* Adapt_Segmenter::helpID [protected]
char Adapt_Segmenter::label[100] [protected]
Reimplemented from Train_Segmenter.
TrainPhoneModel** Adapt_Segmenter::masterAdapt [protected]
double Adapt_Segmenter::maxDistance [protected]
TrainPhoneModel** Adapt_Segmenter::mergeTestMod [protected]
double Adapt_Segmenter::mergeWinThreshold [protected]
int* Adapt_Segmenter::modelMapping [protected]
int Adapt_Segmenter::nrCompareModels [protected]
double* Adapt_Segmenter::pTable1 [protected]
double* Adapt_Segmenter::pTable2 [protected]
int Adapt_Segmenter::pTlen [protected]
int Adapt_Segmenter::segAmount [protected]
int Adapt_Segmenter::segInitID [protected]
int Adapt_Segmenter::systemID [protected]
int Adapt_Segmenter::ubm_word_amount [protected]
int Adapt_Segmenter::winnerM1 [protected]
Referenced by proceedMerge().
int Adapt_Segmenter::winnerM2 [protected]
Referenced by proceedMerge().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:42:44 2010 for 'shout' by doxygen 1.5.8.