SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
Whisper Class Reference
Whisper is the top-level class of the decoder.
Public Member Functions
Whisper (ShoutConfig *myConfig)
~Whisper ()
Protected Member Functions
int getClusterID (FeaturePool *fPool)
Protected Attributes
int numberOfModels
int numberOfClusters
int numberOfClusteredModels
int vectorSize
PhoneModel ** clusterModels
PhoneModel ** models
LexicalTree * myTree
LexicalTree * myBackgroundTree
LexicalTree * myPhoneLoop
LanguageModel * myLM
FeaturePool * vtlnStream [VTLN_STEPS]
SegmentationAdmin readPool_curSeg
Detailed Description
Whisper is the top-level class of the decoder.
The constructor Whisper::Whisper() handles everything. It requires file names for the acoustic models (PhoneModel), the lexical tree (LexicalTree) the language model (LanguageModel) and a list of files to decode.
Next to LM decoding, it is also possible to do forced allignment with Whisper. In this case the file-list file must contain the correct sentences after the feature labels. Each sentence must start with the language model history. In most cases this is (<s> <s>).
Constructor & Destructor Documentation
Whisper::Whisper (ShoutConfig * myConfig)
All code is run in this constructor. It loads the LanguageModel, the PhoneModel and the LexicalTree. The decoding is done in the LexicalTree.
References PhoneModel::adapt_clear(), LexicalTree::addForcedAlignOOV(), LexicalTree::alignmentIsEmpty(), LexicalTree::borrowPhoneString(), LexicalTree::checkAMs(), FeaturePool::claimSegmentationID(), clusterModels, FeaturePool::createNewPool(), doPhoneAlignment, FILE_TYPE_RAW_DECODING, WriteFileLittleBigEndian::freadEndianSafe(), LexicalTree::getBestRecognition(), FeaturePool::getCurInfoString(), FeaturePool::getCurSegmentLen(), FeaturePool::getCurSegmentStart(), FeaturePool::getFirstVectorFirstSegment(), FeaturePool::getFirstVectorNextSegment(), ShoutConfig::getFloatValue(), LanguageModel::getNumberOfWords(), FeaturePool::getSegmentID(), ShoutConfig::getStringValue(), FeaturePool::getVector(), FeaturePool::getVectorList(), LexicalTree::initialiseTree(), LexicalTree::latticeBaumWelch_backward(), LexicalTree::latticeBaumWelch_calculatePosteriors(), LexicalTree::latticeBaumWelch_forward(), LexicalTree::latticeBaumWelch_initBackward(), LexicalTree::latticeBaumWelch_initForward(), LexicalTree::latticeBaumWelch_mmi_accumulatorsPosteriors(), LexicalTree::latticeBaumWelch_numberNodes(), LexicalTree::latticeBaumWelch_setLikelihoods(), FastMath::log(), models, myBackgroundTree, myLM, myPhoneLoop, myTree, numberOfClusteredModels, numberOfClusters, numberOfModels, LexicalTree::overwritePrunePars(), LexicalTree::overwriteWeightPars(), ShoutConfig::parIsDefined(), LexicalTree::printFinalSettings(), LexicalTree::printInitialSettings(), LexicalTree::printLattice(), LexicalTree::printNBestList(), LexicalTree::processVector(), readPool_curSeg, FeaturePool::readRTTM(), LexicalTree::safeBestRecognition(), LexicalTree::setAMs(), LexicalTree::setForcedAlign(), LexicalTree::setInitialLMHistory(), LexicalTree::setLattice(), LexicalTree::setLatticeGeneration(), LexicalTree::setLM(), LexicalTree::setPhoneLoop(), StringFunctions::splitList(), vectorSize, and PhoneModel::writeAccumulators().
Whisper::~Whisper ()
The destructor cleans up all models.
References clusterModels, models, myBackgroundTree, myLM, myTree, numberOfClusteredModels, and numberOfClusters.
Member Function Documentation
int Whisper::getClusterID (FeaturePool * fPool) [protected]
Determine the cluster ID
References clusterModels, PhoneModel::getLogPDFProbability(), FeaturePool::getNextVector(), FeaturePool::getVector(), numberOfClusters, and readPool_curSeg.
Member Data Documentation
PhoneModel** Whisper::clusterModels [protected]
Referenced by getClusterID(), Whisper(), and ~Whisper().
PhoneModel** Whisper::models [protected]
Referenced by Whisper(), and ~Whisper().
LexicalTree* Whisper::myBackgroundTree [protected]
Referenced by Whisper(), and ~Whisper().
LanguageModel* Whisper::myLM [protected]
Referenced by Whisper(), and ~Whisper().
LexicalTree* Whisper::myPhoneLoop [protected]
Referenced by Whisper().
LexicalTree* Whisper::myTree [protected]
Referenced by Whisper(), and ~Whisper().
int Whisper::numberOfClusteredModels [protected]
Referenced by Whisper(), and ~Whisper().
int Whisper::numberOfClusters [protected]
Referenced by getClusterID(), Whisper(), and ~Whisper().
int Whisper::numberOfModels [protected]
Referenced by Whisper().
SegmentationAdmin Whisper::readPool_curSeg [protected]
Referenced by getClusterID(), and Whisper().
int Whisper::vectorSize [protected]
Referenced by Whisper().
FeaturePool* Whisper::vtlnStream[VTLN_STEPS] [protected]
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:38 2010 for 'shout' by doxygen 1.5.8.