SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
Shout_VTLN Class Reference
Public Member Functions
Shout_VTLN (char *method, char *AMFile, char *audioRttmIn, char *audioName, char *audioRttmOut, double *totals)
~Shout_VTLN ()
int getVtlnFactor ()
Private Attributes
int lastSpeakerVTLN
Detailed Description
Todo:
Documentation
Constructor & Destructor Documentation
Shout_VTLN::Shout_VTLN (char * method, char * AMFile, char * audioRttmIn, char * audioName, char * audioRttmOut, double * totals)
Todo:
Documentation
References FeaturePool::claimSegmentationID(), FeaturePool::createNewPool(), FILE_TYPE_RAW_VTLN, WriteFileLittleBigEndian::freadEndianSafe(), FeaturePool::getCurSegmentLen(), FeaturePool::getCurSegmentStart(), FeaturePool::getFirstVectorFirstSegment(), FeaturePool::getFirstVectorNextSegment(), PhoneModel::getLogPDFProbability(), FeaturePool::getNumberOfSpeakers(), FeaturePool::getSpeakerID(), lastSpeakerVTLN, FeaturePool::readRTTM(), FeaturePool::setSegmentID(), and FeaturePool::writeRTTM().
Shout_VTLN::~Shout_VTLN ()
Todo:
Documentation
Member Function Documentation
int Shout_VTLN::getVtlnFactor ()
Todo:
Documentation
References lastSpeakerVTLN.
Member Data Documentation
int Shout_VTLN::lastSpeakerVTLN [private]
Referenced by getVtlnFactor(), and Shout_VTLN().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:22 2010 for 'shout' by doxygen 1.5.8.