SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
Shout_Cluster Class Reference
This class is the base class for the shout_cluster application. It segments an audio file based on the speaker clustering procedure from the Train_Speaker_Segmenter class.
Public Member Functions
Shout_Cluster (char *featureFile, char *label, char *inputRTTM_train, char *inputRTTM_decode, char *outputRTTM, char *fea2, double initWeight, char *fea3, int fastMerge, int maxClusters, bool widen)
~Shout_Cluster ()
Protected Attributes
Adapt_Segmenter * segmenter
Train_Segmenter * segmenter
Detailed Description
This class is the base class for the shout_cluster application. It segments an audio file based on the speaker clustering procedure from the Train_Speaker_Segmenter class.
Constructor & Destructor Documentation
Shout_Cluster::Shout_Cluster (char * featureFile, char * label, char * inputRTTM_train, char * inputRTTM_decode, char * outputRTTM, char * featureFile2, double initWeight, char * featureFile3, int fastMerge, int maxClusters, bool widen)
This constructor reads a feature file in order to segment and cluster it.
Energy based Speaker Activity Detection is used for a first rough speech/non-speech clustering. After that, the method in Train_Speaker_Segmenter is used to obtain a speaker segmentation.
References FeaturePool::claimSegmentationID(), FeaturePool::createNewMultiStreamPool(), FeaturePool::createNewPool(), FeaturePool::enableFilter(), FILE_TYPE_RAW_DIARIZATION, FILE_TYPE_SHOUT, FILE_TYPE_TEXT, FeaturePool_Multistream_file::fileName, FeaturePool_Multistream_file::fileType, FeaturePool::getPoolLength(), FeaturePool::readRTTM(), segmenter, and Train_Segmenter::train().
Shout_Cluster::~Shout_Cluster ()
The destructor is empty.
Member Data Documentation
Train_Segmenter* Shout_Cluster::segmenter [protected]
Adapt_Segmenter* Shout_Cluster::segmenter [protected]
Referenced by Shout_Cluster().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:20 2010 for 'shout' by doxygen 1.5.8.