SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutTrainMMI Class Reference
Public Member Functions
ShoutTrainMMI (char *amIn, char *amOut, char *enumFile, char *denomFile)
~ShoutTrainMMI ()
Constructor & Destructor Documentation
ShoutTrainMMI::ShoutTrainMMI (char * amIn, char * amOut, char * enumFile, char * denomFile)
Todo:
Docs
References WriteFileLittleBigEndian::freadEndianSafe(), TrainPhoneModel::trainMMI(), and PhoneModel::writeModel().
ShoutTrainMMI::~ShoutTrainMMI ()
Todo:
Docs
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:25 2010 for 'shout' by doxygen 1.5.8.