SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutPrepareAdapt Class Reference
This class is the main class of shout_prepare_adapt.
Public Member Functions
ShoutPrepareAdapt (FILE *amFile, char *dblFile, int maxClusters, char *outDblName)
~ShoutPrepareAdapt ()
Protected Member Functions
void adaptingModel (PhoneModel *model)
Detailed Description
This class is the main class of shout_prepare_adapt.
Constructor & Destructor Documentation
ShoutPrepareAdapt::ShoutPrepareAdapt (FILE * inFile, char * dblName, int nrClusters, char * outDblName)
Todo:
Docs
References PhoneModel::adapt_clear(), TrainPhoneModel::adapt_setAcTrain(), adaptingModel(), FeaturePool::addFeatureFile(), FeaturePool::addSegment(), FeaturePool::claimSegmentationID(), FILE_TYPE_RAW_DECODING, WriteFileLittleBigEndian::freadEndianSafe(), TrainPhoneModel::getKLDistance(), PhoneModel::getLogPDFProbability(), FeaturePool::getPoolLength(), FeaturePool::getVector(), FeaturePool::resetSegmentation(), TrainPhoneModel::setTrainingData(), and TrainPhoneModel::train().
ShoutPrepareAdapt::~ShoutPrepareAdapt ()
The destructor cleans up administration.
Member Function Documentation
void ShoutPrepareAdapt::adaptingModel (PhoneModel * model) [protected]
Todo:
add documentation
References PhoneModel::adapt_adapt(), PhoneModel::adapt_clear(), PhoneModel::adapt_setInitialNode(), PhoneModel::dim(), PhoneModel::isSilModel(), Adapt_AM_TreeNode::meanGaussian, Adapt_AM_TreeNode::setHelperMatrices_1(), and Adapt_AM_TreeNode::setHelperMatrices_2().
Referenced by ShoutPrepareAdapt().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:23 2010 for 'shout' by doxygen 1.5.8.