SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
ShoutTrainFinishSAT Class Reference
Public Member Functions
ShoutTrainFinishSAT (char *traindir, char *satlist, char *am, int modelNr)
~ShoutTrainFinishSAT ()
Constructor & Destructor Documentation
ShoutTrainFinishSAT::ShoutTrainFinishSAT (char * traindir, char * satlist, char * am, int modelNr)
References TrainPhoneModel::appendSAT(), TrainPhoneModel::finishSAT(), WriteFileLittleBigEndian::freadEndianSafe(), PhoneModel::isSilModel(), and PhoneModel::writeModel().
ShoutTrainFinishSAT::~ShoutTrainFinishSAT ()
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:25 2010 for 'shout' by doxygen 1.5.8.