SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
FastMath Namespace Reference
Functions
void initLog ()
float log (float val)
Variables
static float logLookupTable [FASTLOG_2_POW_20]
Detailed Description
Fast implementation of log by Laurent de Soras, adjusted to table-lookup by people at ICSI
Function Documentation
void FastMath::initLog ()
Fast implementation of log by Laurent de Soras, adjusted to table-lookup by people at ICSI
References logLookupTable.
float FastMath::log (float val) [inline]
Referenced by TrainPhoneModel::baumWelch(), Gaussian::calculateCP(), LanguageModel_Segmenter::finishModel(), MixGaussian::getLogP(), MixGaussian::getLookaheadLogP(), MixGaussian::initializeFastCalc(), main(), Gaussian::mapAdaptMean(), PhoneModel::PhoneModel(), TrainPhoneModel::train(), Gaussian::trainFinish(), Gaussian::trainMMI(), TrainPhoneModel::TrainPhoneModel(), TrainPhoneModel::viterbi(), and Whisper::Whisper().
Variable Documentation
float FastMath::logLookupTable[FASTLOG_2_POW_20] [static]
Referenced by initLog().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:46 2010 for 'shout' by doxygen 1.5.8.