SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
WriteFileLittleBigEndian Namespace Reference
Functions
int fwriteEndianSafe (void *var, int nrTimes, int nrBytes, FILE *file)
int freadEndianSafe (void *var, int nrTimes, int nrBytes, FILE *file)
Detailed Description
Some methods for reading and writing to file, big/little-endian safe.
Function Documentation
int WriteFileLittleBigEndian::freadEndianSafe (void * var, int nrTimes, int nrBytes, FILE * file)
Todo:
docs
Referenced by Adapt_AM::Adapt_AM(), Gaussian::addAccumulators(), Gaussian::appendSAT(), ArticulatoryStream::ArticulatoryStream(), Shout_MakeTrainSet::checkDataDir(), FeaturePool::createNewPool(), FeatureExtraction::FeatureExtraction(), Hash::Hash(), LanguageModel::LanguageModel(), LexicalTree::LexicalTree(), Train_Segmenter::loadClusters(), MergeTrainSet::MergeTrainSet(), MixGaussian::MixGaussian(), MultiMixGaussian::MultiMixGaussian(), PhoneModel::PhoneModel(), FeatureExtraction::readAudioWindow(), Vector::readData(), Vector::readFloatData(), FeaturePool::readHeader_ShoutFormat(), TrainPhoneModel::readModel(), SpeakerRecognition::readModel(), LexicalTree::readTree(), SpkrecStats::readUbmModel(), SpeakerRecognition::readUbmModel(), Segmenter::Segmenter(), FeaturePool::setFilter(), Shout_lm2bin::Shout_lm2bin(), Shout_MakeTrainSet::Shout_MakeTrainSet(), Shout_Preprocess::Shout_Preprocess(), Shout_VTLN::Shout_VTLN(), ShoutMergeAm::ShoutMergeAm(), ShoutOnline::ShoutOnline(), ShoutPrepareAdapt::ShoutPrepareAdapt(), ShoutTrainFinish::ShoutTrainFinish(), ShoutTrainFinishSAT::ShoutTrainFinishSAT(), ShoutTrainMMI::ShoutTrainMMI(), ShoutTrainModel::ShoutTrainModel(), Train_Segmenter::Train_Segmenter(), Gaussian::trainMMI(), TrainPhoneModel::TrainPhoneModel(), and Whisper::Whisper().
int WriteFileLittleBigEndian::fwriteEndianSafe (void * var, int nrTimes, int nrBytes, FILE * file)
Todo:
docs
Referenced by Shout_lm2bin::Shout_lm2bin(), ShoutOnline::ShoutOnline(), TrainHash::storeHash(), and SpeakerRecognition::writeModel().
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:46 2010 for 'shout' by doxygen 1.5.8.