SHoUT speech recognition toolkit
SHoUT
by Marijn Huijbregts
home
manual
API
download
thesis
contact
StringFunctions Namespace Reference
Functions
void RightTrim (char *str)
void splitList (char *str, char *str2)
void splitRef (char *str, char *str2)
Detailed Description
Some methods that operate on strings
Function Documentation
void StringFunctions::RightTrim (char * str)
This global function strips all spaces and tabs at the end of a string.
Referenced by ShoutConfig::fillParameter(), and Shout_lm2bin::Shout_lm2bin().
void StringFunctions::splitList (char * str, char * str2)
This function splits the first string in two parts at the place of the first space or tab character from the left. The second part is placed in str2, the first in str.
Referenced by FeatureExtraction::doFeatureExtraction(), FeaturePool::fillBuffer_TextFormat(), ShoutConfig::fillParameter(), FeaturePool::readHeader_TextFormat(), FeaturePool::readRTTM(), Shout_lm2bin::Shout_lm2bin(), and Whisper::Whisper().
void StringFunctions::splitRef (char * str, char * str2)
This function removes the label from the reference string. The label is stored in str2.
Website design by Free CSS Templates
The software documented in this manual is developed by Marijn Huijbregts,
© Copyright 2005, 2006, 2007, 2008, 2009, 2010, all rights reserved.
This manual is generated on Tue Dec 7 11:43:46 2010 for 'shout' by doxygen 1.5.8.